## Recurrent Neural Network (RNN)

Not like Sequential neural networks that we have been using, RNNs are networks with loops in them, allowing information to persist.

Pytorch has better examples and clear defination of the hidden state hence is used in this example to show the parameters in a simple RNN. The actual LSTM or GRU have more complicated structures

<center><img src="https://github.com/jtao/AdvancedML/blob/main/images/RNN_unrolled.png?raw=1" width="600"/><br/>Credit: colah.github.io</center>

In [1]:
import torch
from torchsummary import summary
rnn = torch.nn.RNN(10, 2, 1)
input = torch.randn(1, 3, 10)
h0 = torch.randn(1, 3, 2)
output, hn = rnn(input, h0)

In [2]:
for p in rnn.parameters():
    print(p)

Parameter containing:
tensor([[ 0.2361, -0.2594, -0.3566, -0.5244, -0.1461,  0.1667, -0.3963, -0.4134,
         -0.0260,  0.0139],
        [-0.6028,  0.6335,  0.0098, -0.6904, -0.5671,  0.2644,  0.2656,  0.5480,
         -0.1348, -0.2807]], requires_grad=True)
Parameter containing:
tensor([[-0.0360, -0.5383],
        [ 0.4553, -0.2628]], requires_grad=True)
Parameter containing:
tensor([-0.5872, -0.0482], requires_grad=True)
Parameter containing:
tensor([-0.2039,  0.4515], requires_grad=True)


In [3]:
pytorch_total_params = sum(p.numel() for p in rnn.parameters() if p.requires_grad)
pytorch_total_params

28